name: Build Kernel

on:
  workflow_call:
    inputs: &workflow_inputs
      kernel_defconfig:
        description: Kernel - Defconfig
        type: string
        required: false
        default: grus
      ksu:
        description: With KernelSU
        type: boolean
        required: false
        default: false
      kernel_localversion:
        description: Kernel - Local Version
        type: string
        required: false
        default: wabby-wabbo
      ksu_setup_script:
        description: KernelSU - Setup Script
        type: string
        required: false
        default: https://raw.githubusercontent.com/backslashxx/KernelSU/master/kernel/setup.sh
      ksu_setup_branch:
        description: KernelSU - Setup Branch
        type: string
        required: false
        default: master
      prebuilt_gcc_toolchain:
        description: Prebuilt - GCC Toolchain
        type: string
        required: false
        default: https://github.com/ketikai/android_kernel_xiaomi_sdm710/releases/download/prebuilt/linaro-gcc.tar.xz
      prebuilt_clang_toolchain:
        description: Prebuilt - Clang Toolchain
        type: string
        required: false
        default: https://github.com/ketikai/android_kernel_xiaomi_sdm710/releases/download/prebuilt/proton-clang.tar.xz
      prebuilt_anykernel:
        description: Prebuilt - AnyKernel
        type: string
        required: false
        default: https://github.com/ketikai/android_kernel_xiaomi_sdm710/releases/download/prebuilt/anykernel.tar.xz
  workflow_dispatch:
    inputs: *workflow_inputs
    
env:
  TOOLCHAIN_DIR: 'toolchain'
  OUTPUT_DIR: 'build'
  BUILD_ARTIFACT: kernel
  ASSAMBLE_ARTIFACT: anykernel

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CC: clang
      CROSS_COMPILE: aarch64-linux-gnu-
      CROSS_COMPILE_ARM32: arm-linux-gnueabi-
      CROSS_TRIPLE: aarch64-linux-gnu-
      ARCH: arm64
      SUBARCH: arm64
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Export Environment Variables
      env:
        KERNEL_DEFCONFIG: ${{ inputs.kernel_defconfig }}
        KERNEL_LOCALVERSION: ${{ inputs.kernel_localversion }}
        PREBUILT_GCC_TOOLCHAIN: ${{ inputs.prebuilt_gcc_toolchain }}
        PREBUILT_CLANG_TOOLCHAIN: ${{ inputs.prebuilt_clang_toolchain }}
      run: |
        echo "DEFCONFIG=${KERNEL_DEFCONFIG}_defconfig" >> ${GITHUB_ENV}
        if [[ -n "${KERNEL_LOCALVERSION}" ]]; then
          echo "LOCALVERSION=-${KERNEL_LOCALVERSION}" >> ${GITHUB_ENV}
        fi
        echo "WORKER_SIZE=$(( $(nproc) * 2 - 1 ))" >> ${GITHUB_ENV}
        echo "PREBUILT_GCC_TOOLCHAIN=${PREBUILT_GCC_TOOLCHAIN}" >> ${GITHUB_ENV}
        echo "PREBUILT_CLANG_TOOLCHAIN=${PREBUILT_CLANG_TOOLCHAIN}" >> ${GITHUB_ENV}

        mkdir -p ${TOOLCHAIN_DIR}
        echo "${PREBUILT_GCC_TOOLCHAIN}" > ${TOOLCHAIN_DIR}/.PREBUILT_GCC_TOOLCHAIN
        echo "${PREBUILT_CLANG_TOOLCHAIN}" > ${TOOLCHAIN_DIR}/.PREBUILT_CLANG_TOOLCHAIN

    - name: Download Prebuilt GCC Toolchain From Cache
      uses: actions/cache@v6
      id: cache_prebuilt_gcc_toolchain
      with:
        path: ${{ env.TOOLCHAIN_DIR }}/gcc
        key: ${{ runner.os }}-${{ runner.arch }}-prebuilt-gcc-toolchain-${{ hashFiles(format('{0}/.PREBUILT_GCC_TOOLCHAIN', env.TOOLCHAIN_DIR)) }}

    - name: Download Prebuilt GCC Toolchain
      if: steps.cache_prebuilt_gcc_toolchain.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${TOOLCHAIN_DIR}/gcc/
        pushd ${TOOLCHAIN_DIR}
        wget -O - ${PREBUILT_GCC_TOOLCHAIN} | tar -xJvf - -C gcc
        popd

    - name: Download Prebuilt Clang Toolchain From Cache
      uses: actions/cache@v6
      id: cache_prebuilt_clang_toolchain
      with:
        path: ${{ env.TOOLCHAIN_DIR }}/clang/
        key: ${{ runner.os }}-${{ runner.arch }}-prebuilt-clang-toolchain-${{ hashFiles(format('{0}/.PREBUILT_CLANG_TOOLCHAIN', env.TOOLCHAIN_DIR)) }}

    - name: Download Prebuilt Clang Toolchain
      if: steps.cache_prebuilt_clang_toolchain.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${TOOLCHAIN_DIR}/clang
        pushd ${TOOLCHAIN_DIR}
        wget -O - ${PREBUILT_CLANG_TOOLCHAIN} | tar -xJvf - -C clang
        popd

    - name: Setup Prebuilt Toolchain
      run: |
        CLANG_TOOLCHAIN="$PWD/${TOOLCHAIN_DIR}/clang/bin"
        GCC_ARM64_TOOLCHAIN="$PWD/${TOOLCHAIN_DIR}/gcc/aarch64-linux-gnu/bin"
        GCC_ARM_TOOLCHAIN="$PWD/${TOOLCHAIN_DIR}/gcc/arm-linux-gnueabi/bin"
        ls -ahl $CLANG_TOOLCHAIN
        ls -ahl $GCC_ARM64_TOOLCHAIN
        ls -ahl $GCC_ARM_TOOLCHAIN
        echo "PATH=\"${CLANG_TOOLCHAIN}:${GCC_ARM64_TOOLCHAIN}:${GCC_ARM_TOOLCHAIN}:$PATH\"" >> ${GITHUB_ENV}

    - name: KernelSU Integration
      env:
        KSU: ${{ inputs.ksu }}
        KSU_SETUP_SCRIPT: ${{ inputs.ksu_setup_script }}
        KSU_SETUP_BRANCH: ${{ inputs.ksu_setup_branch }}
      run: |
        if ${KSU}; then
          curl -LSs ${KSU_SETUP_SCRIPT} | bash -s ${KSU_SETUP_BRANCH}
        fi

    - name: Make Config
      run: |
        make O=${OUTPUT_DIR} ${DEFCONFIG}

    - name: Detect External Signing Key
      run: |
        if [[ -n "${{ secrets.SIGNING_KEY }}" ]]; then
          SIGNING_KEY_FILE=${PWD}/certs/external_signing_key.pem
          echo "${{ secrets.SIGNING_KEY }}" > ${SIGNING_KEY_FILE}
          scripts/config --file ${OUTPUT_DIR}/.config --set-str MODULE_SIG_KEY ${SIGNING_KEY_FILE}
          make O=${OUTPUT_DIR} oldconfig
        fi

    - name: Make Image
      run: |
        make O=${OUTPUT_DIR} -j${WORKER_SIZE}

    - name: Upload Kernel
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.BUILD_ARTIFACT }}
        path: |
          ${{ env.OUTPUT_DIR }}/arch/arm64/boot/Image
        if-no-files-found: error
  
  assamble:
    runs-on: ubuntu-22.04
    needs: 
    - build
    steps:
    - name: Download Prebuilt AnyKernel
      env:
        PREBUILT_ANYKERNEL: ${{ inputs.prebuilt_anykernel }}
      run: |
        mkdir -p ${OUTPUT_DIR}
        wget -O - ${PREBUILT_ANYKERNEL} | tar -xJvf - -C ${OUTPUT_DIR}

    - name: Download Kernel
      uses: actions/download-artifact@v8
      with:
        name: ${{ env.BUILD_ARTIFACT }}
        path: ${{ env.BUILD_ARTIFACT }}

    - name: Setup Kernel
      run: |
        cp ${BUILD_ARTIFACT}/Image ${OUTPUT_DIR}/

    - name: Upload AnyKernel
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.ASSAMBLE_ARTIFACT }}
        path: |
          ${{ env.OUTPUT_DIR }}/*
        if-no-files-found: error
        include-hidden-files: true
