name: Build Kernel

on:
  workflow_call:
    inputs: &workflow_inputs
      kernel_arch:
        description: Kernel - Arch
        type: string
        required: false
        default: arm64
      kernel_device:
        description: Kernel - Device
        type: string
        required: false
        default: grus
      llvm:
        description: Use LLVM/Clang
        type: boolean
        required: false
        default: true
      verbose:
        description: Enable more detailed logs
        type: boolean
        required: false
        default: false
      ksu:
        description: With KernelSU
        type: boolean
        required: false
        default: false
      kernel_localversion:
        description: Kernel - Local Version
        type: string
        required: false
        default: wabby-wabbo
      ksu_setup_script:
        description: KernelSU - Setup Script
        type: string
        required: false
        default: https://raw.githubusercontent.com/backslashxx/KernelSU/master/kernel/setup.sh
      ksu_setup_branch:
        description: KernelSU - Setup Branch
        type: string
        required: false
        default: master
      prebuilt_gcc_toolchain:
        description: Prebuilt - GCC Toolchain
        type: string
        required: false
        default: https://github.com/ketikai/android_kernel_xiaomi_sdm710/releases/download/prebuilt/linaro-gcc.tar.xz
      prebuilt_clang_toolchain:
        description: Prebuilt - Clang Toolchain
        type: string
        required: false
        default: https://github.com/ketikai/android_kernel_xiaomi_sdm710/releases/download/prebuilt/proton-clang.tar.xz
      prebuilt_anykernel_package:
        description: Prebuilt - AnyKernel Package
        type: string
        required: false
        default: https://github.com/ketikai/android_kernel_xiaomi_sdm710/releases/download/prebuilt/anykernel.tar.xz
  workflow_dispatch:
    inputs: *workflow_inputs
    
env:
  DESTINATION_DIR: .target
  BUILD_ARTIFACT: kernel
  ASSAMBLE_ARTIFACT: anykernel

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Prepare Prebuilt 
      id: prepare_prebuilt
      env:
        TOOLCHAIN_DIR: .prebuilt/toolchain
      run: |
        DIR="${{ env.TOOLCHAIN_DIR }}/gcc"
        mkdir -p $DIR
        echo "GCC_TOOLCHAIN_DIR=$DIR" >> $GITHUB_OUTPUT
        CACHE_KEY="${{ env.TOOLCHAIN_DIR }}/.GCC_TOOLCHAIN_CACHE_KEY"
        echo "${{ inputs.prebuilt_gcc_toolchain }}" > $CACHE_KEY
        echo "GCC_TOOLCHAIN_CACHE_KEY=$CACHE_KEY" >> $GITHUB_OUTPUT

        DIR="${{ env.TOOLCHAIN_DIR }}/clang"
        mkdir -p $DIR
        echo "CLANG_TOOLCHAIN_DIR=$DIR" >> $GITHUB_OUTPUT
        CACHE_KEY="${{ env.TOOLCHAIN_DIR }}/.CLANG_TOOLCHAIN_CACHE_KEY"
        echo "${{ inputs.prebuilt_clang_toolchain }}" > $CACHE_KEY
        echo "CLANG_TOOLCHAIN_CACHE_KEY=$CACHE_KEY" >> $GITHUB_OUTPUT

    - name: Download Prebuilt GCC Toolchain From Cache
      uses: actions/cache@v6
      id: prebuilt_gcc_toolchain_cache
      with:
        path: ${{ steps.prepare_prebuilt.outputs.GCC_TOOLCHAIN_DIR }}
        key: ${{ runner.os }}-${{ runner.arch }}-prebuilt-gcc-toolchain-${{ hashFiles(steps.prepare_prebuilt.outputs.GCC_TOOLCHAIN_CACHE_KEY) }}

    - name: Download Prebuilt GCC Toolchain
      if: steps.prebuilt_gcc_toolchain_cache.outputs.cache-hit != true
      run: |
        wget -O - ${{ inputs.prebuilt_gcc_toolchain }} | tar -xJvf - -C ${{ steps.prepare_prebuilt.outputs.GCC_TOOLCHAIN_DIR }}

    - name: Download Prebuilt Clang Toolchain From Cache
      uses: actions/cache@v6
      id: prebuilt_clang_toolchain_cache
      with:
        path: ${{ steps.prepare_prebuilt.outputs.CLANG_TOOLCHAIN_DIR }}
        key: ${{ runner.os }}-${{ runner.arch }}-prebuilt-clang-toolchain-${{ hashFiles(steps.prepare_prebuilt.outputs.CLANG_TOOLCHAIN_CACHE_KEY) }}

    - name: Download Prebuilt Clang Toolchain
      if: steps.prebuilt_clang_toolchain_cache.outputs.cache-hit != true
      run: |
        wget -O - ${{ inputs.prebuilt_clang_toolchain }} | tar -xJvf - -C ${{ steps.prepare_prebuilt.outputs.CLANG_TOOLCHAIN_DIR }}

    - name: KernelSU Integration
      run: |
        if ${{ inputs.ksu }}; then
          curl -LSs ${{ inputs.ksu_setup_script }} | bash -s ${{ inputs.ksu_setup_branch }}
        fi

    - name: Execute assamble
      run: |
        LLVM=$(${{ inputs.llvm }} && echo "--llvm" || echo "")
        VERSION=$([[ -n "${{ inputs.kernel_localversion }}" ]] && echo "--version ${{ inputs.kernel_localversion }}" || echo "")
        SIGNING=$([[ -n "${{ secrets.SIGNING_KEY }}" ]] && echo "${{ secrets.SIGNING_KEY }}" > ".signing_key.pem"; echo "-s .signing_key.pem" || echo "")
        VERBOSE=$(${{ inputs.verbose }} && echo "-v" || echo "")
        ./assamble ${{ inputs.kernel_arch }} ${{ inputs.kernel_device }} $LLVM $VERSION $SIGNING $VERBOSE -d ${{ env.DESTINATION_DIR }}

    - name: Upload Kernel And Modules
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.BUILD_ARTIFACT }}
        path: |
          ${{ env.DESTINATION_DIR }}/*
        if-no-files-found: error
  
  assamble:
    runs-on: ubuntu-22.04
    needs: 
    - build
    steps:
    - name: Download Prebuilt AnyKernel Package
      run: |
        mkdir -p ${{ env.DESTINATION_DIR }}
        wget -O - ${{ inputs.prebuilt_anykernel_package }} | tar -xJvf - -C ${{ env.DESTINATION_DIR }}

    - name: Download Kernel
      uses: actions/download-artifact@v8
      with:
        name: ${{ env.BUILD_ARTIFACT }}
        path: ${{ env.BUILD_ARTIFACT }}

    - name: Setup Kernel Image
      run: |
        cp "${{ env.BUILD_ARTIFACT }}/kernel/Image" "${{ env.DESTINATION_DIR }}"

    - name: Upload AnyKernel Package
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.ASSAMBLE_ARTIFACT }}
        path: |
          ${{ env.DESTINATION_DIR }}/*
        if-no-files-found: error
