name: Build Kernel

on:
  workflow_call:
    inputs: &workflow_inputs
      verbose_logs:
        description: More detailed logs
        type: boolean
        required: false
        default: false
      kernel_arch:
        description: Kernel - Arch
        type: string
        required: false
        default: arm64
      kernel_device:
        description: Kernel - Device
        type: string
        required: false
        default: grus
      kernel_localversion:
        description: Kernel - Local Version
        type: string
        required: false
        default: wabby-wabbo
      kernel_cross_compile:
        description: Kernel - Cross Compile
        type: string
        required: false
        default: aarch64-linux-gnu
      kernel_custom_env:
        description: Kernel - Custom ENV
        type: string
        required: false
        default: CROSS_COMPILE_ARM32=arm-linux-gnueabi-
      llvm:
        description: Use LLVM / Clang
        type: boolean
        required: false
        default: true
      prebuilt_clang_toolchain:
        description: Prebuilt - Clang Toolchain
        type: string
        required: false
        default: https://github.com/ketikai/android_kernel_xiaomi_sdm710/releases/download/prebuilt/clang-r596125.tar.xz
      prebuilt_gcc_toolchain:
        description: Prebuilt - GCC Toolchain
        type: string
        required: false
        default: https://github.com/ketikai/android_kernel_xiaomi_sdm710/releases/download/prebuilt/linaro-gcc.tar.xz
      ksu:
        description: With KernelSU
        type: boolean
        required: false
        default: false
      ksu_setup_script:
        description: KernelSU - Setup Script
        type: string
        required: false
        default: https://raw.githubusercontent.com/backslashxx/KernelSU/master/kernel/setup.sh
      ksu_setup_branch:
        description: KernelSU - Setup Branch
        type: string
        required: false
        default: master
      anykernel:
        description: Assemble AnyKernel
        type: boolean
        required: false
        default: true
      prebuilt_anykernel_package:
        description: Prebuilt - AnyKernel Package
        type: string
        required: false
        default: https://github.com/ketikai/android_kernel_xiaomi_sdm710/releases/download/prebuilt/anykernel.tar.xz
  workflow_dispatch:
    inputs: *workflow_inputs
    
env:
  PREBUILT_DIR: .prebuilt
  DESTINATION_DIR: .target
  BUILD_ARTIFACT: kernel
  ASSEMBLE_ARTIFACT: anykernel

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Prepare Prebuilt
      id: prepare_prebuilt
      env:
        TOOLCHAIN_DIR: ${{ env.PREBUILT_DIR }}/toolchain
      run: |
        if ${{ inputs.llvm }}; then
          DIR="${{ env.TOOLCHAIN_DIR }}/clang"
          mkdir -p $DIR
          echo "CLANG_TOOLCHAIN_DIR=$DIR" >> $GITHUB_OUTPUT
          CACHE_KEY="${{ env.TOOLCHAIN_DIR }}/.CLANG_TOOLCHAIN_CACHE_KEY"
          echo "${{ inputs.prebuilt_clang_toolchain }}" > $CACHE_KEY
          echo "CLANG_TOOLCHAIN_CACHE_KEY=$CACHE_KEY" >> $GITHUB_OUTPUT
        else
          DIR="${{ env.TOOLCHAIN_DIR }}/gcc"
          mkdir -p $DIR
          echo "GCC_TOOLCHAIN_DIR=$DIR" >> $GITHUB_OUTPUT
          CACHE_KEY="${{ env.TOOLCHAIN_DIR }}/.GCC_TOOLCHAIN_CACHE_KEY"
          echo "${{ inputs.prebuilt_gcc_toolchain }}" > $CACHE_KEY
          echo "GCC_TOOLCHAIN_CACHE_KEY=$CACHE_KEY" >> $GITHUB_OUTPUT
        fi

    - name: Download Prebuilt Clang Toolchain From Cache
      uses: actions/cache@v6
      id: prebuilt_clang_toolchain_cache
      if: inputs.llvm == true
      with:
        path: ${{ steps.prepare_prebuilt.outputs.CLANG_TOOLCHAIN_DIR }}
        key: ${{ runner.os }}-${{ runner.arch }}-prebuilt-clang-toolchain-${{ hashFiles(steps.prepare_prebuilt.outputs.CLANG_TOOLCHAIN_CACHE_KEY) }}

    - name: Download Prebuilt Clang Toolchain
      if: inputs.llvm == true && steps.prebuilt_clang_toolchain_cache.outputs.cache-hit != true
      run: |
        wget -nv -O - ${{ inputs.prebuilt_clang_toolchain }} | tar -xJvf - -C ${{ steps.prepare_prebuilt.outputs.CLANG_TOOLCHAIN_DIR }}

    - name: Download Prebuilt GCC Toolchain From Cache
      uses: actions/cache@v6
      id: prebuilt_gcc_toolchain_cache
      if: inputs.llvm == false
      with:
        path: ${{ steps.prepare_prebuilt.outputs.GCC_TOOLCHAIN_DIR }}
        key: ${{ runner.os }}-${{ runner.arch }}-prebuilt-gcc-toolchain-${{ hashFiles(steps.prepare_prebuilt.outputs.GCC_TOOLCHAIN_CACHE_KEY) }}

    - name: Download Prebuilt GCC Toolchain
      if: inputs.llvm == false && steps.prebuilt_gcc_toolchain_cache.outputs.cache-hit != true
      run: |
        wget -nv -O - ${{ inputs.prebuilt_gcc_toolchain }} | tar -xJvf - -C ${{ steps.prepare_prebuilt.outputs.GCC_TOOLCHAIN_DIR }}

    - name: KernelSU Integration
      run: |
        if ${{ inputs.ksu }}; then
          curl -LSs ${{ inputs.ksu_setup_script }} | bash -s ${{ inputs.ksu_setup_branch }}
        fi

    - name: Execute assemble
      run: |
        VERBOSE=$(${{ inputs.verbose_logs }} && echo "-v" || echo "")
        LLVM=$(${{ inputs.llvm }} && echo "--llvm" || echo "")
        CROSS_COMPILE=$([[ -n "${{ inputs.kernel_cross_compile }}" ]] && echo "--cross ${{ inputs.kernel_cross_compile }}" || echo "")
        VERSION=$([[ -n "${{ inputs.kernel_localversion }}" ]] && echo "--version ${{ inputs.kernel_localversion }}" || echo "")
        SIGNING=$([[ -n "${{ secrets.SIGNING_KEY }}" ]] && echo "${{ secrets.SIGNING_KEY }}" > ".signing_key.pem"; echo "-s .signing_key.pem" || echo "")
        CUSTOM_CONFIG=$([[ -n "${{ inputs.kernel_custom_env }}" ]] && echo "${{ inputs.kernel_custom_env }}" || echo "")
        ./assemble ${{ inputs.kernel_arch }} ${{ inputs.kernel_device }} $VERBOSE -p ${{ env.PREBUILT_DIR }} $LLVM $CROSS_COMPILE $VERSION $SIGNING -d ${{ env.DESTINATION_DIR }} $CUSTOM_CONFIG

    - name: Upload Kernel And Modules
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.BUILD_ARTIFACT }}
        path: |
          ${{ env.DESTINATION_DIR }}/*
        if-no-files-found: error
        overwrite: true
        include-hidden-files: true
  
  assemble:
    runs-on: ubuntu-22.04
    needs: 
    - build
    if: inputs.anykernel == true
    steps:
    - name: Download Prebuilt AnyKernel Package
      run: |
        mkdir -p ${{ env.DESTINATION_DIR }}
        wget -O - ${{ inputs.prebuilt_anykernel_package }} | tar -xJvf - -C ${{ env.DESTINATION_DIR }}

    - name: Download Kernel
      uses: actions/download-artifact@v8
      with:
        name: ${{ env.BUILD_ARTIFACT }}
        path: ${{ env.BUILD_ARTIFACT }}

    - name: Setup Kernel Image
      run: |
        cp "${{ env.BUILD_ARTIFACT }}/kernel/Image" "${{ env.DESTINATION_DIR }}"

    - name: Upload AnyKernel Package
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.ASSEMBLE_ARTIFACT }}
        path: |
          ${{ env.DESTINATION_DIR }}/*
        if-no-files-found: error
        overwrite: true
        include-hidden-files: true
